# -*- coding: utf-8 -*-
"""final03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oz9VuqGezbvdr1NmxEyIeRUYfqzIiTNC
"""

print("สวัสดีครับ ยินดีต้อนรับสู่โปรแกรมคำนวณเกรดจากคะแนน")
print("ชื่อผู้พัฒนา : นายญาณพัฒน์ ปุยละเทิม ม. 4/4 เลขที่ 3")
score = int(input("Enter your score : "))
if score >= 80:
            print("Grade A ")
elif score >= 70:
            print("Grade B ")
elif score >= 60:
            print("Grade C ")
elif score >= 50:
            print("Grade D ")
else:
            print("Grade F ")

import random

def start_app():
    # โค้ดสีสำหรับตกแต่ง Terminal
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    ORANGE = '\033[33m'
    RED = '\033[91m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    RESET = '\033[0m'
    BOLD = '\033[1m'

    # ส่วนต้อนรับและชื่อผู้พัฒนา
    print(f"{CYAN}{'='*50}{RESET}")
    print(f"{BOLD}{BLUE}🌟 ยินดีต้อนรับสู่ระบบคำนวณเกรดอัจฉริยะ 🌟{RESET}")
    print(f"{BOLD}ผู้พัฒนา: นายญาณพัฒน์ ปุยละเทิม ม. 4/4 เลขที่ 3{RESET}")
    print(f"{CYAN}{'='*50}{RESET}")

    # คลังคำชมและกำลังใจสุ่มตามเกรด
    feedbacks = {
        "A": [f"{GREEN}ยอดเยี่ยมที่สุด! รักษามาตรฐานนี้ไว้นะครับ{RESET}", f"{GREEN}สุดยอด! ความพยายามของคุณสัมฤทธิ์ผลแล้ว{RESET}"],
        "B": [f"{YELLOW}เก่งมากครับ! อีกนิดเดียวจะแตะ A แล้วนะ{RESET}", f"{YELLOW}ผลลัพธ์น่าภูมิใจมาก พัฒนาต่อไปนะครับ{RESET}"],
        "C": [f"{ORANGE}ผ่านไปได้ด้วยดีครับ ลองทบทวนจุดที่พลาดอีกนิดนะ{RESET}", f"{ORANGE}ทำได้ดีแล้วครับ เป็นกำลังใจให้เก่งขึ้นไปอีก{RESET}"],
        "D": [f"{ORANGE}ผ่านเกณฑ์นะ! เทอมหน้าลองฟิตกว่านี้อีกนิด รับรองรุ่ง{RESET}", f"{ORANGE}สู้ๆ ครับ พยายามอีกหน่อยเกรดพุ่งแน่นอน{RESET}"],
        "F": [f"{RED}ไม่เป็นไรนะ! ล้มได้ก็ลุกได้ ครั้งหน้าเอาใหม่ สู้ๆ!{RESET}", f"{RED}ครั้งนี้พลาดไป ไม่ได้แปลว่าคุณไม่เก่ง พยายามต่อยากระตุก!{RESET}"]
    }

    while True:
        try:
            print(f"\n{BOLD}กรอกคะแนน (0-100) หรือพิมพ์ 'exit' เพื่อจบการทำงาน{RESET}")
            user_input = input("Enter score: ").strip().lower()

            if user_input == 'exit':
                print(f"\n{BLUE}ขอบคุณที่ใช้งานครับ ขอให้โชคดีกับการเรียน! 👋{RESET}")
                break

            score = float(user_input)

            # ตรวจสอบช่วงคะแนน
            if score < 0 or score > 100:
                print(f"{RED}⚠️ ข้อผิดพลาด: คะแนนต้องอยู่ระหว่าง 0 - 100 เท่านั้น!{RESET}")
                continue

            # ตรรกะการตัดเกรดและเลือกสี
            if score >= 80:
                grade, color = "A", GREEN
            elif score >= 70:
                grade, color = "B", YELLOW
            elif score >= 60:
                grade, color = "C", ORANGE
            elif score >= 50:
                grade, color = "D", ORANGE
            else:
                grade, color = "F", RED

            # สุ่มคำชม
            comment = random.choice(feedbacks[grade])

            # แสดงผลลัพธ์
            print(f"{BOLD}------------------------------{RESET}")
            print(f"📊 ผลคะแนนของคุณ: {BOLD}{score}{RESET}")
            print(f"🏆 เกรดที่ได้: {BOLD}{color}{grade}{RESET}")
            print(f"✨ ข้อความจากระบบ: {comment}")
            print(f"{BOLD}------------------------------{RESET}")

        except ValueError:
            print(f"{RED}❌ กรุณากรอกเฉพาะ 'ตัวเลข' เท่านั้นครับ!{RESET}")

if __name__ == "__main__":
    start_app()

import random
import os
import time

# --- การตั้งค่าสี (ANSI Colors) ---
GREEN  = '\033[92m'
YELLOW = '\033[93m'
ORANGE = '\033[33m'
RED    = '\033[91m'
BLUE   = '\033[94m'
CYAN   = '\033[96m'
BOLD   = '\033[1m'
RESET  = '\033[0m'

FILENAME = "grade_history.txt"

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def save_to_file(name, score, grade):
    """บันทึกข้อมูลลงไฟล์ text"""
    try:
        with open(FILENAME, "a", encoding="utf-8") as file:
            timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
            file.write(f"{timestamp} | ชื่อ: {name:<10} | คะแนน: {score:>5} | เกรด: {grade}\n")
    except Exception as e:
        print(f"{RED}เกิดข้อผิดพลาดในการบันทึก: {e}{RESET}")

def view_history():
    """ฟังก์ชันเช็คประวัติย้อนหลัง"""
    clear_screen()
    print(f"{CYAN}{'='*60}{RESET}")
    print(f"{BOLD}{BLUE}📜 ประวัติการบันทึกเกรดทั้งหมด{RESET}")
    print(f"{CYAN}{'='*60}{RESET}")

    if not os.path.exists(FILENAME):
        print(f"{ORANGE}ยังไม่มีข้อมูลประวัติในขณะนี้...{RESET}")
    else:
        with open(FILENAME, "r", encoding="utf-8") as file:
            content = file.read()
            if content.strip() == "":
                print(f"{ORANGE}ประวัติว่างเปล่า...{RESET}")
            else:
                print(content)

    print(f"{CYAN}{'='*60}{RESET}")
    input(f"\nกด {BOLD}Enter{RESET} เพื่อกลับสู่เมนูหลัก...")

def start_app():
    # คลังคำชมแบบสุ่ม
    feedbacks = {
        "A": [f"{GREEN}สุดยอด!{RESET} ความพยายามของคุณน่าชื่นชมที่สุด", f"สมบูรณ์แบบ! {GREEN}คุณคือแรงบันดาลใจของเพื่อนๆ{RESET}"],
        "B": [f"{YELLOW}เก่งมาก!{RESET} อีกนิดเดียวจะแตะ A แล้ว สู้ต่ออีกนิดนะ", f"ทำได้ดีมาก {YELLOW}ภูมิใจในตัวเองได้เลยนะครับ{RESET}"],
        "C": [f"ผ่านมาได้แล้ว! {ORANGE}ลองทบทวนจุดที่พลาด รับรองเก่งขึ้นแน่{RESET}", f"ทำได้ดีครับ {ORANGE}พัฒนาต่อไปอย่างต่อเนื่องนะ{RESET}"],
        "D": [f"ผ่านเกณฑ์ครับ! {ORANGE}ครั้งหน้าลองวางแผนใหม่ให้ดีกว่านี้ สู้ๆ{RESET}", f"เป็นกำลังใจให้ {ORANGE}คุณมีศักยภาพที่จะทำได้ดีกว่านี้{RESET}"],
        "F": [f"{RED}ไม่เป็นไรนะ!{RESET} ความพยายามครั้งหน้าสำคัญกว่าวันนี้ อย่าท้อ!", f"ล้มแล้วลุกคือคนเก่ง {RED}ผมเชื่อว่าคุณทำได้ดีขึ้นในครั้งหน้า!{RESET}"]
    }

    while True:
        clear_screen()
        print(f"{CYAN}{'='*60}{RESET}")
        print(f"{BOLD}{BLUE}🌟 ระบบบริหารจัดการเกรดอัจฉริยะ (Smart Grade System){RESET}")
        print(f"{BOLD}ผู้พัฒนา: นายญาณพัฒน์ ปุยละเทิม ม. 4/4 เลขที่ 3{RESET}")
        print(f"{CYAN}{'='*60}{RESET}")
        print(f"1. {GREEN}คำนวณเกรดใหม่{RESET}")
        print(f"2. {YELLOW}เช็คประวัติย้อนหลัง{RESET}")
        print(f"3. {RED}ออกจากโปรแกรม{RESET}")
        print(f"{CYAN}{'='*60}{RESET}")

        choice = input(f"{BOLD}เลือกรายการ (1-3): {RESET}").strip()

        if choice == '1':
            name = input(f"\n{CYAN}👤 ชื่อนักเรียน: {RESET}").strip()
            if not name:
                print(f"{RED}❌ ต้องระบุชื่อ!{RESET}"); time.sleep(1); continue

            try:
                score_input = input(f"{CYAN}📝 คะแนน (0-100): {RESET}").strip()
                score = float(score_input)

                if 0 <= score <= 100:
                    # ตรรกะการตัดเกรด
                    if score >= 80: grade, color = "A", GREEN
                    elif score >= 70: grade, color = "B", YELLOW
                    elif score >= 60: grade, color = "C", ORANGE
                    elif score >= 50: grade, color = "D", ORANGE
                    else: grade, color = "F", RED

                    # บันทึกข้อมูล
                    save_to_file(name, score, grade)

                    # แสดง Visual Feedback
                    clear_screen()
                    print(f"\n{color}{'—'*45}{RESET}")
                    print(f"{BOLD}ผลลัพธ์ของคุณ {name}{RESET}")
                    print(f"📊 คะแนน: {BOLD}{score}{RESET}")
                    print(f"🏆 เกรดที่ได้: {BOLD}{color}[ {grade} ]{RESET}")
                    print(f"✨ {random.choice(feedbacks[grade])}")
                    print(f"{color}{'—'*45}{RESET}")
                    print(f"{GREEN}💾 ระบบบันทึกข้อมูลเรียบร้อยแล้ว!{RESET}")
                    input(f"\nกด {BOLD}Enter{RESET} เพื่อกลับหน้าหลัก...")
                else:
                    print(f"{RED}⚠️ คะแนนต้องอยู่ระหว่าง 0-100!{RESET}"); time.sleep(1)
            except ValueError:
                print(f"{RED}❌ ข้อผิดพลาด: กรุณากรอกตัวเลขเท่านั้น!{RESET}"); time.sleep(1)

        elif choice == '2':
            view_history()
        elif choice == '3':
            print(f"\n{BLUE}ขอบคุณที่ใช้งานโปรแกรมครับคุณญาณพัฒน์ ขอให้โชคดี! 👋{RESET}")
            break
        else:
            print(f"{RED}⚠️ กรุณาเลือก 1, 2 หรือ 3 เท่านั้น{RESET}"); time.sleep(1)

if __name__ == "__main__":
    start_app()