# -*- coding: utf-8 -*-
"""mid-03-Torsin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wfzv5zt2B4_wtN31hcKyjhRyMGrIvnv9

# ยินดีต้อนรับสู่ Colab
"""

electricity = float(input("จำนวนไฟฟ้าที่ใช้ :"))
if electricity > 150:
  print("ค่าไฟทั้งหมด",electricity * 5 ,"บาท")
else:
  print("ค่าไฟทั้งหมด",electricity *3 ,"บาท")